# Site settings
title: Jeff Carroll's Awesome Website
email: jdcarroll@fullsail.edu
description: > # this means to ignore newlines until "baseurl:"
  I am passionate to discover as much about web development as I possibly can while here at full sail.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jdcarroll.github.io" # the base hostname & protocol for your site
twitter_username: "@unbelievablife"
github_username:  jdcarroll

# Build settings
markdown: kramdown
